BordSpellen/Controllers/BoardGameController.cs
using BordSpellen.Models;
using Core.Domain.Data.Entities;
using Core.Domain.Security.Roles;
using Core.Repositories.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BordSpellen.Controllers;

[Authorize(Roles = UserRoles.Organiser)]
public class BoardGameController : Controller
{
    private readonly IBoardGameRepository _boardGameRepository;

    public BoardGameController(IBoardGameRepository boardGameRepository)
    {
        _boardGameRepository = boardGameRepository;
    }
    
    // GET
    public async Task<IActionResult> Index()
    {
        var boardgames = await _boardGameRepository.GetAll();
        return View(nameof(Index), boardgames);
    }
    
    public async  Task<IActionResult> Details(int id)
    {
        var boardGame = await _boardGameRepository.GetById(id);
        if (boardGame == null || boardGame.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        
        return View(boardGame);
    }
    public IActionResult Create()
    {
        return View(nameof(Create), new BoardGameViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(BoardGameViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var newBoardGame = new BoardGame
        {
            Name = viewModel.Name,
            Description = viewModel.Description,
            Genre = viewModel.Genre,
            HasAgeRestriction = viewModel.HasAgeRestriction,
            ImageFormat = viewModel.Image.ContentType,
            Type = viewModel.Type
        };

        var memoryStream = new MemoryStream();
        await viewModel.Image.CopyToAsync(memoryStream);
        newBoardGame.Image = memoryStream.ToArray();

        await _boardGameRepository.Create(newBoardGame);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Edit(int id)
    {
        var boardGameResponse = await _boardGameRepository.GetById(id);
        if (boardGameResponse == null || boardGameResponse.Id != id || String.IsNullOrEmpty(id.ToString()) || id != boardGameResponse.Id)
        {
            return View("NotFound");
        }

        BoardGameViewModel? viewModel;
        if (boardGameResponse.Image != null)
        {
            viewModel = new BoardGameViewModel
            {
                Id = boardGameResponse.Id,
                Name = boardGameResponse.Name,
                Description = boardGameResponse.Description,
                Picture = Convert.ToBase64String(boardGameResponse.Image),
                PictureFormat = boardGameResponse.ImageFormat,
                HasAgeRestriction = boardGameResponse.HasAgeRestriction,
                Genre = boardGameResponse.Genre,
                Type = boardGameResponse.Type
            };
            return View(viewModel);
        }
        
        viewModel = new BoardGameViewModel
        {
            Id = boardGameResponse.Id,
            Name = boardGameResponse.Name,
            Description = boardGameResponse.Description,
            HasAgeRestriction = boardGameResponse.HasAgeRestriction,
            Genre = boardGameResponse.Genre,
            Type = boardGameResponse.Type
        };
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, BoardGameViewModel viewModel)
    {
       
        if (id != viewModel.Id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var result = viewModel.HasAgeRestriction;
        
        var newBoardGame = new BoardGame
        {
            Id = viewModel.Id,
            Name = viewModel.Name,
            Description = viewModel.Description,
            HasAgeRestriction = viewModel.HasAgeRestriction,
            ImageFormat = viewModel.Image.ContentType,
            Genre = viewModel.Genre,
            Type = viewModel.Type
        };
        
        var memoryStream = new MemoryStream();
        await viewModel.Image.CopyToAsync(memoryStream);
        newBoardGame.Image = memoryStream.ToArray();
        
        await _boardGameRepository.Update(newBoardGame);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Delete(int id)
    {
        var boardGame = await _boardGameRepository.GetById(id);
        if (boardGame == null || boardGame.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");

        await _boardGameRepository.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

BordSpellen/Controllers/DietController.cs
using BordSpellen.Models;
using Core.Domain.Data.Entities;
using Core.Domain.Security.Roles;
using Core.Repositories.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BordSpellen.Controllers;

[Authorize(Roles = UserRoles.Organiser)]
public class DietController : Controller
{
    private readonly IDietRepository _dietRepository;

    public DietController(IDietRepository dietRepository)
    {
        _dietRepository = dietRepository;
    }
    
    // GET
    public async Task<IActionResult> Index()
    {
        var diets = await _dietRepository.GetAll();
        return View(diets);
    }
    public async Task<IActionResult> Details(int id)
    {
        var diet = await _dietRepository.GetById(id);
        if (diet == null || diet.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        return View(diet);
    }
    public IActionResult Create()
    {
        return View(new DietViewModel());
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(DietViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var newDiet = new Diet
        {
            Name = viewModel.Name,
            Description = viewModel.Description
        };

        await _dietRepository.Create(newDiet);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Edit(int id)
    {
        var dietResponse = await _dietRepository.GetById(id);
        if (dietResponse == null && id != dietResponse?.Id) return View("NotFound");
        
        var viewModel = new DietViewModel
        {
            Id = dietResponse.Id,
            Name = dietResponse.Name,
            Description = dietResponse.Description
        };
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, DietViewModel viewModel)
    {
        if (id != viewModel.Id) return View("NotFound");
        
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var newDiet = new Diet
        {
            Id = viewModel.Id,
            Name = viewModel.Name,
            Description = viewModel.Description
        };
        
        await _dietRepository.Update(newDiet);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Delete(int id)
    {
        var diet = await _dietRepository.GetById(id);
        if (diet == null) return View("NotFound");

        await _dietRepository.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

BordSpellen/Controllers/ReviewController.cs
using BordSpellen.Models;
using Core.Domain.Security;
using Core.Domain.Security.Roles;
using Core.Repositories.Data.Actors;
using Core.Repositories.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BordSpellen.Controllers;

[Authorize(Roles = UserRoles.User)]
public class ReviewController : Controller
{
    private readonly IReviewRepository _reviewRepository;
    private readonly IPersonRepository _personRepository;
    private readonly IGameEventRepository _gameEventRepository;
    private readonly UserManager<BoardGameUser> _userManager;

    public ReviewController(IReviewRepository reviewRepository,
        IPersonRepository personRepository,
        IGameEventRepository gameEventRepository,
        UserManager<BoardGameUser> userManager)
    {
        _reviewRepository = reviewRepository;
        _personRepository = personRepository;
        _gameEventRepository = gameEventRepository;
        _userManager = userManager;
    }
    
    // GET
    public async Task<IActionResult> Index()
    {
        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);
        if (person == null)
        {
            return View("CannotAccess");
        }
        
        var result =  await _gameEventRepository.GetReviewedGameEvents(person);
        var gameEventList = result.Distinct().ToList();
        return View(gameEventList);
    }
    public async Task<IActionResult> Create(int id)
    {
        var gameEvent = await _gameEventRepository.GetById(id, g => g.GamerGameEvents!);
        if (gameEvent == null)
        {
            return View("NotFound");
        }

        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);

        if (gameEvent.GamerGameEvents != null)
        {
            var result = gameEvent.GamerGameEvents.FirstOrDefault(r => r.GameEventId == id && r.PersonId == person!.Id);
            if (result == null || gameEvent.EventDate > DateTime.Now)
            {
                return View("CannotAccess");
            }
        }
        else
        {
            return View("NotFound");
        }

        return View(nameof(Create), new ReviewViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int id, ReviewViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(nameof(Create), viewModel);
        }
        
        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);
        var gameEvent = await _gameEventRepository.GetById(id);

        if (person == null || gameEvent == null)
        {
            return View("NotFound");
        }
        
        var response = await _reviewRepository.CreateReview(viewModel.ToDto(viewModel), person, gameEvent);
        if (response != null) return RedirectToAction(nameof(Index));
        
        TempData["error"] = "Couldn't create review try again later";
        return View(nameof(Create), viewModel);
    }
    public async Task<IActionResult> Update(int id)
    {
        var review = await _reviewRepository.GetById(id);
        if (review == null)
        {
            return View("NotFound");
        }

        var gameEvent = await _gameEventRepository.GetById(review.EventId);
        
        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);
        
        if (review.ReviewPosterId != person!.Id || gameEvent?.EventDate > DateTime.Now)
        {
            return View("CannotAccess");
        }
        
        ReviewViewModel viewModel = new ReviewViewModel
        {
            Id = review.Id,
            Rating = review.Rating,
            ReviewDescription = review.ReviewDescription
        };
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update(int id, ReviewViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }
        
        var review = await _reviewRepository.GetById(id);
        if (review == null)
        {
            return View("NotFound");
        }
        
        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);
        var gameEvent = await _gameEventRepository.GetById(review.EventId);

        viewModel.Id = review.Id;

        if (person == null || gameEvent == null)
        {
            return View("NotFound");
        }
        
        var response = await _reviewRepository.UpdateReview(viewModel.ToDto(viewModel), person, gameEvent);
        return response != null ? RedirectToAction(nameof(Index)) : RedirectToAction("Details", "GameEvent", new { Id = id });
    }
    public async Task<IActionResult> Delete(int id)
    {
        var review = await _reviewRepository.GetById(id);
        if (review == null || String.IsNullOrEmpty(id.ToString()))
        {
            return View("NotFound");
        }
        
        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);
        
        if (review.ReviewPosterId != person!.Id)
        {
            return View("CannotAccess");
        }
        

        await _reviewRepository.Delete(id);
        return RedirectToAction("Index", "GameEvent");
    }
}

BordSpellen/Views/Shared/CannotAccess.cshtml
@{
    ViewData["Title"] = "Cannot Access";
}

<div class="row">
    <div class="col-md-6 offset-3 alert alert-danger text-center">
        <h2>We're sorry!</h2>
        <p>You are unable to access this entity.</p>
        <p>Please, click the button below to be redirected to the home page.</p>
        <hr />
        <p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-success" >Home Page</a>
        </p>
    </div>
</div>

BordSpellen/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<div class="row">
    <div class="col-md-6 offset-3 alert alert-danger text-center">
        <h2>We're sorry!</h2>
        <p>The entity you are trying to access could not be found.</p>
        <p>Please, click the button below to be redirected to the home page.</p>
        <hr />
        <p>
            <a asp-controller="Home" asp-action="Index" class="btn btn-outline-success" >Home Page</a>
        </p>
    </div>
</div>

BordSpellen/Views/Shared/_CreateItem.cshtml
@using Core.Domain.Security.Roles
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole(UserRoles.Organiser))
{
    <div style="position: fixed; right: 25px; bottom: 25px; z-index: 1" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i> Add New </a>
    </div>
}

BordSpellen/Views/Shared/_Identity.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Core.Domain.Security.Roles
@using Core.Domain.Security
@inject UserManager<BoardGameUser> UserManager
@if (!User.Identity.IsAuthenticated)
{
    <ul class="navbar-nav flex-grow-1">
    </ul>
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{
    @if (User.IsInRole(UserRoles.Organiser))
    {
        <ul class="navbar-nav flex-grow-1">
            <li class="navbar-nav">
                <div class="dropdown">
                    <button class="nav-link text-dark btn dropdown-toggle border-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-clipboard"></i> Manage
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" asp-controller="BoardGame" asp-action="Index">
                                <i class="bi bi-joystick"></i> Manage Boardgames
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" asp-controller="Diet" asp-action="Index">
                                <i class="bi bi-egg-fried"></i> Manage Diets
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    }
    else
    {
        <ul class="navbar-nav flex-grow-1">
        </ul>
    }
    
    <div class="dropdown">
        <div class="dropdown">
            <button class="btn btn-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserAsync(User).Result.FullName
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Details" asp-route-id="@UserManager.GetUserAsync(User).Result.Id">
                        <i class="bi bi-person-bounding-box"></i> Account
                    </a>
                </li>
                @if (User.IsInRole(UserRoles.User))
                {
                    <li>
                        <a class="dropdown-item" asp-controller="GameEvent" asp-action="OpedGameEvent">
                            <i class="bi bi-calendar-check"></i> Manage Subscribed Events
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-controller="Review" asp-action="Index">
                            <i class="bi bi-journal"></i> Manage My Reviews
                        </a>
                    </li>
                }

                @if (User.IsInRole(UserRoles.Organiser))
                {
                    <li>
                        <a class="dropdown-item" asp-controller="GameEvent" asp-action="MyGameEvent">
                            <i class="bi bi-calendar4-event"></i> Manage My Events
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
    
    <span style="padding: 5px"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

BordSpellen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>@ViewData["Title"] - BordSpellen</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/BordSpellen.styles.css" asp-append-version="true"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    </head>
    <body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">BordSpellen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="navbar-nav">
                            <a class="nav-link text-dark" asp-controller="GameEvent" asp-action="Index"><i class="bi bi-calendar2-event"></i> Events</a>
                        </li>
                    </ul>
                    <partial name="_Identity.cshtml"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid fill-height">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>