BordSpellen/Models/BoardGameViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BordSpellen.Models.Generic;
using Core.Domain.Dto.Entities;
using Core.Domain.Enums;

namespace BordSpellen.Models;

public class BoardGameViewModel : BaseViewModel<BoardGameDto, BoardGameViewModel>
{
    [Display(Name = "Game name")]
    [Required(ErrorMessage = "Game name is required")]
    public string? Name { get; set; }
    
    [Display(Name = "Game description")]
    [Required(ErrorMessage = "Game description is required")]
    public string? Description { get; set; }
    
    [Display(Name = "Game genre")]
    [Required(ErrorMessage = "Game genre is required")]
    public BoardGameGenre Genre { get; set; }
    
    [Display(Name = "is game 18+")]
    [Required(ErrorMessage = "18+ check is required")]
    public bool HasAgeRestriction { get; set; }

    [Display(Name = "Game image")]
    [Required(ErrorMessage = "Game image is required")]
    public IFormFile Image { get; set; }

    [Display(Name = "Game type")]
    [Required(ErrorMessage = "Game type is required")]
    public BoardGameType Type { get; set; }
    
    [NotMapped]
    public string? Picture { get; set; }
    [NotMapped]
    public string? PictureFormat { get; set; }
    
    public override BoardGameDto ToDto(BoardGameViewModel model)
    {
        throw new NotImplementedException();
    }
}

BordSpellen/Controllers/BoardGameController.cs
using BordSpellen.Models;
using Core.Domain.Data.Entities;
using Core.Domain.Security.Roles;
using Core.Repositories.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BordSpellen.Controllers;

[Authorize(Roles = UserRoles.Organiser)]
public class BoardGameController : Controller
{
    private readonly IBoardGameRepository _boardGameRepository;

    public BoardGameController(IBoardGameRepository boardGameRepository)
    {
        _boardGameRepository = boardGameRepository;
    }
    
    // GET
    public async Task<IActionResult> Index()
    {
        var boardgames = await _boardGameRepository.GetAll();
        return View(nameof(Index), boardgames);
    }
    
    public async  Task<IActionResult> Details(int id)
    {
        var boardGame = await _boardGameRepository.GetById(id);
        if (boardGame == null || boardGame.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        
        return View(boardGame);
    }
    public IActionResult Create()
    {
        return View(nameof(Create), new BoardGameViewModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(BoardGameViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var newBoardGame = new BoardGame
        {
            Name = viewModel.Name,
            Description = viewModel.Description,
            Genre = viewModel.Genre,
            HasAgeRestriction = viewModel.HasAgeRestriction,
            ImageFormat = viewModel.Image.ContentType,
            Type = viewModel.Type
        };

        var memoryStream = new MemoryStream();
        await viewModel.Image.CopyToAsync(memoryStream);
        newBoardGame.Image = memoryStream.ToArray();

        await _boardGameRepository.Create(newBoardGame);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Edit(int id)
    {
        var boardGameResponse = await _boardGameRepository.GetById(id);
        if (boardGameResponse == null || boardGameResponse.Id != id || String.IsNullOrEmpty(id.ToString()) || id != boardGameResponse.Id)
        {
            return View("NotFound");
        }

        BoardGameViewModel? viewModel;
        if (boardGameResponse.Image != null)
        {
            viewModel = new BoardGameViewModel
            {
                Id = boardGameResponse.Id,
                Name = boardGameResponse.Name,
                Description = boardGameResponse.Description,
                Picture = Convert.ToBase64String(boardGameResponse.Image),
                PictureFormat = boardGameResponse.ImageFormat,
                HasAgeRestriction = boardGameResponse.HasAgeRestriction,
                Genre = boardGameResponse.Genre,
                Type = boardGameResponse.Type
            };
            return View(viewModel);
        }
        
        viewModel = new BoardGameViewModel
        {
            Id = boardGameResponse.Id,
            Name = boardGameResponse.Name,
            Description = boardGameResponse.Description,
            HasAgeRestriction = boardGameResponse.HasAgeRestriction,
            Genre = boardGameResponse.Genre,
            Type = boardGameResponse.Type
        };
        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, BoardGameViewModel viewModel)
    {
       
        if (id != viewModel.Id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        if (!ModelState.IsValid)
        {
            return View(viewModel);
        }

        var result = viewModel.HasAgeRestriction;
        
        var newBoardGame = new BoardGame
        {
            Id = viewModel.Id,
            Name = viewModel.Name,
            Description = viewModel.Description,
            HasAgeRestriction = viewModel.HasAgeRestriction,
            ImageFormat = viewModel.Image.ContentType,
            Genre = viewModel.Genre,
            Type = viewModel.Type
        };
        
        var memoryStream = new MemoryStream();
        await viewModel.Image.CopyToAsync(memoryStream);
        newBoardGame.Image = memoryStream.ToArray();
        
        await _boardGameRepository.Update(newBoardGame);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Delete(int id)
    {
        var boardGame = await _boardGameRepository.GetById(id);
        if (boardGame == null || boardGame.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");

        await _boardGameRepository.Delete(id);
        return RedirectToAction(nameof(Index));
    }
}

BordSpellen/Controllers/GameEventController.cs
using BordSpellen.Models;
using BordSpellen.Models.ViewModels;
using Core.Domain.Security;
using Core.Domain.Security.Roles;
using Core.Infrastructure.Helper;
using Core.Repositories.Data.Actors;
using Core.Repositories.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BordSpellen.Controllers;

public class GameEventController : Controller
{
    private readonly IGameEventRepository _gameEventRepository;
    private readonly IBoardGameRepository _boardGameRepository;
    private readonly IDietRepository _dietRepository;
    private readonly IPersonRepository _personRepository;
    private readonly IReviewRepository _reviewRepository;
    private readonly UserManager<BoardGameUser> _userManager;

    public GameEventController(
        IGameEventRepository gameEventRepository,
        IBoardGameRepository boardGameRepository,
        IDietRepository dietRepository,
        IPersonRepository personRepository,
        IReviewRepository reviewRepository,
        UserManager<BoardGameUser> userManager)
    {
        _gameEventRepository = gameEventRepository;
        _boardGameRepository = boardGameRepository;
        _dietRepository = dietRepository;
        _personRepository = personRepository;
        _userManager = userManager;
        _reviewRepository = reviewRepository;
    }
    
    
    [AllowAnonymous]
    // GET
    public async Task<IActionResult> Index()
    {
        var events = await _gameEventRepository.GetAll(
            r => r.GamerGameEvents!,
            r => r.Organiser!);
        return View(nameof(Index), events);
    }
    
    [AllowAnonymous]
    public async Task<IActionResult> Details(int id)
    {
        var gameEventDetails = await _gameEventRepository.GetById(id);
        if (gameEventDetails == null || gameEventDetails.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        
        if (User is {Identity.IsAuthenticated: true})
        {
            var identityUser = await _userManager.GetUserAsync(User);
            var person = await _personRepository.GetOneByEmail(identityUser.Email);
            var gameEvent = await _gameEventRepository.GetById(id, g => g.GamerGameEvents!);
            var subscription = gameEvent?.GamerGameEvents!.FirstOrDefault(ge =>
                ge.PersonId == person!.Id && ge.GameEventId == gameEvent.Id);

            if (subscription == null)
            {
                TempData["Subscription"] = "false";
            }
            else
            {
                TempData["Subscription"] = "true";
            }
        }

        TempData["Average"] = await _reviewRepository.GetAverageOrganiserRating(gameEventDetails.Organiser!);
        
        return View(nameof(Details), gameEventDetails);
    }
    
    [Authorize(Roles = UserRoles.Organiser)]
    public async Task<IActionResult> Create()
    {
        var userEmail = await _userManager.GetEmailAsync(await _userManager.GetUserAsync(User));
        var person = await _personRepository.GetOneByEmail(userEmail);

        if (person == null)
        {
            return RedirectToAction("AccessDenied", "Account");
        }

        DateTime date = person.DateOfBirth ?? DateTime.Today;
        if (Helper.Age(date) < 18)
        {
            TempData["error"] = "You must be 18 year or older to organise an Event!";
            return RedirectToAction(nameof(Index));
        }


        var dropdownData = await GetDropdownViewModel();

        ViewBag.boardGames = new SelectList(dropdownData.BoardGameEvents, "Id", "Name");
        ViewBag.diets = new SelectList(dropdownData.AvailableFoodTypes, "Id", "Name");
        
        return View(nameof(Create),new GameEventViewModel());
    }

    [HttpPost]
    [Authorize(Roles = UserRoles.Organiser)]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(GameEventViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            var dropdownData = await GetDropdownViewModel();

            ViewBag.boardGames = new SelectList(dropdownData.BoardGameEvents, "Id", "Name");
            ViewBag.diets = new SelectList(dropdownData.AvailableFoodTypes, "Id", "Name");
            
            return View(nameof(Create), viewModel);
        }

        var organiser = await _personRepository.GetOneByEmail(
            await _userManager.GetEmailAsync(
                await _userManager.GetUserAsync(User)
            )
        );

        if (organiser == null) return View("NotFound");
        
        viewModel.Organiser = organiser;
        await _gameEventRepository.Create(viewModel.ToDto(viewModel));
        return RedirectToAction(nameof(Index));
    }
    
    [Authorize(Roles = UserRoles.Organiser)]
    public async Task<IActionResult> Edit(int id)
    {
        var gameEvent =  await _gameEventRepository.GetById(id, g => g.Organiser!,
            g => g.AvailableFoodTypes!,
            g => g.GamerGameEvents!,
            g => g.ReviewsRecieved!,
            g => g.BoardGameEvents!);
        if (gameEvent == null || id != gameEvent.Id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");
        if (await _userManager.GetEmailAsync(await _userManager.GetUserAsync(User)) != gameEvent.Organiser!.Email)
        {
            return RedirectToAction("AccessDenied", "Account");
        }

        if (gameEvent.EventDate < DateTime.Now)
        {
            TempData["error"] = "Cannot edit expired events!";
            return RedirectToAction("Index");
        }

        if (gameEvent.GamerGameEvents?.Count > 0 ||
            gameEvent.ReviewsRecieved?.Count > 0)
            return View("CannotAccess");

        var response = new GameEventViewModel
        {
            Id = gameEvent.Id,
            Name = gameEvent.Name,
            Description = gameEvent.Description,
            Street = gameEvent.Street,
            HouseNumber = gameEvent.HouseNumber,
            PostalCode = gameEvent.PostalCode,
            City = gameEvent.City,
            EventDate = gameEvent.EventDate,
            IsAdultEvent = gameEvent.IsAdultEvent,
            MaxAmountOfPlayers = gameEvent.MaxAmountOfPlayers,
            Organiser = gameEvent.Organiser,
            BoardGameIds = gameEvent.BoardGameEvents?.Select(b => b.BoardGameId).ToList(),
            DietIds = gameEvent.AvailableFoodTypes?.Select(b => b.DietId).ToList()
        };

        var dropdownData = await GetDropdownViewModel();

        ViewBag.boardGames = new SelectList(dropdownData.BoardGameEvents, "Id", "Name");
        ViewBag.diets = new SelectList(dropdownData.AvailableFoodTypes, "Id", "Name");
        
        return View(nameof(Edit),response);
    }

    [HttpPost]
    [Authorize(Roles = UserRoles.Organiser)]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, GameEventViewModel viewModel)
    {
        if (id != viewModel.Id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");

        if (!ModelState.IsValid)
        {
            var dropdownData = await GetDropdownViewModel();

            ViewBag.boardGames = new SelectList(dropdownData.BoardGameEvents, "Id", "Name");
            ViewBag.diets = new SelectList(dropdownData.AvailableFoodTypes, "Id", "Name");
            return View(nameof(Edit), viewModel);
        }

        await _gameEventRepository.Update(viewModel.ToDto(viewModel));
        return RedirectToAction(nameof(Index));
    }
    
    [Authorize(Roles = UserRoles.Organiser)]
    public async Task<IActionResult> Delete(int id) 
    {
        var gameEvent = await _gameEventRepository.GetById(id, g => g.Organiser!,
            g=> g.GamerGameEvents!);
        if (gameEvent == null || gameEvent.Id != id || String.IsNullOrEmpty(id.ToString())) return View("NotFound");

        if (gameEvent.GamerGameEvents?.Count > 0)
            return View("CannotAccess");
        
        if (await _userManager.GetEmailAsync(await _userManager.GetUserAsync(User)) != gameEvent.Organiser!.Email)
           return RedirectToAction("AccessDenied", "Account");
        

        await _gameEventRepository.Delete(id);
        return RedirectToAction(nameof(Index));
    }
    
    [Authorize(Roles = UserRoles.User)]
    public async Task<IActionResult> Subscribe(int id)
    {
        var identityUser = await _userManager.GetUserAsync(User);
        var person = await _personRepository.GetOneByEmail(identityUser.Email);
        var gameEvent = await _gameEventRepository.GetById(id);
        
        if (person == null || gameEvent == null)
        {
            return View("CannotAccess");
        }

        if (gameEvent.EventDate < DateTime.Now)
        {
            return View("CannotAccess");
        }
        
        if (person.Id == gameEvent.OrganiserId)
        {
            TempData["error"] = "You are the organiser of this event";
            return RedirectToAction(nameof(Details), new { id = gameEvent.Id });
        }
        
        if (gameEvent.IsAdultEvent)
        {
            DateTime date = person.DateOfBirth ?? DateTime.Today;
            var personAge = Helper.Age(date);
            if (personAge < 18)
            {
                TempData["error"] = "This event is for 18 or older";
                return RedirectToAction(nameof(Details), new { id = gameEvent.Id });
            }
        }
        
        if (gameEvent.GamerGameEvents?.Count + 1 > gameEvent.MaxAmountOfPlayers)
        {
            TempData["error"] = "Subscribe limit exceeded";
            return RedirectToAction(nameof(Details), new { id = gameEvent.Id });
        }

        if (await _gameEventRepository.CheckSubscription(gameEvent, person))
        {
            TempData["error"] = "You cannot be subscribed to multiple events on the same day";
            return RedirectToAction(nameof(Details), new { id = gameEvent.Id }); 
        }

BordSpellen/Views/BoardGame/Create.cshtml
@using Core.Domain.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BoardGameViewModel
@{
    ViewData["Title"] = "Create BoardGame";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Boardgame</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-8">
                            <label asp-for="Image" class="control-label"></label>
                            <input asp-for="Image" accept="image/*" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="HasAgeRestriction" class="control-label"></label>
                            <input asp-for="HasAgeRestriction" class="form-control form-check-input p-3" type="checkbox" value="false" onchange="this.value = this.checked" />
                            <span asp-validation-for="HasAgeRestriction" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Genre" class="control-label"></label>
                            <select asp-for="Genre" class="form-control form-select" asp-items="Html.GetEnumSelectList<BoardGameGenre>()"></select>
                            <span asp-validation-for="Genre" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Type" class="control-label"></label>
                            <select asp-for="Type" class="form-control form-select" asp-items="Html.GetEnumSelectList<BoardGameType>()"></select>
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group pt-2">
                        <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BordSpellen/Views/BoardGame/Details.cshtml
@using Core.Domain.Security.Roles
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using BordSpellen.Util
@model Core.Domain.Data.Entities.BoardGame
@{
    ViewData["Title"] = "Create BoardGame";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details of @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" readonly/>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" readonly/>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-8">
                            <label asp-for="Image" class="control-label"></label><br>
                            <img class="rounded-circle mt-1" src="@Model.ImageStringFromByteArray()" alt="@Model.Name" style="max-width: 150px"/>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="HasAgeRestriction" class="control-label"></label> <br>
                            @if (Model.HasAgeRestriction)
                            {
                                <span class="indicator badge bg-danger rounded-circle text-white mt-1">18+</span>
                            }
                            else
                            {
                                <span class="indicator badge bg-success rounded-circle text-white mt-1"><del>18+</del></span>
                            }
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6 mt-2">
                            
                            <label asp-for="Genre" class="control-label"></label><br>
                            <span class="indicator badge bg-info text-white mt-1"> @Model.Genre.ToString() </span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Type" class="control-label"></label><br>
                            <span class="indicator badge bg-info text-white mt-1"> @Model.Type.ToString() </span>
                        </div>
                    </div>
                    
                    @if (User.Identity!.IsAuthenticated && User.IsInRole(UserRoles.User))
                    {
                        <div class="form-group pt-2">
                            <a class="btn btn-outline-danger float-end" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                            <a class="btn btn-outline-warning float-end mx-2" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                            <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                        </div>
                    }
                    else
                    {
                        <div class="form-group pt-2">
                            <a class="btn btn-outline-secondary" asp-controller="GameEvent" asp-action="Index">Go Back</a>
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

BordSpellen/Views/BoardGame/Edit.cshtml
@using Core.Domain.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model BoardGameViewModel
@{
    ViewData["Title"] = "Create BoardGame";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Boardgame @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Description" class="control-label"></label>
                            <input asp-for="Description" class="form-control" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-8">
                            <label asp-for="Image" class="control-label"></label>
                            <input asp-for="Image" type="file" accept="image/*" />
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="HasAgeRestriction" class="control-label"></label>
                            <input asp-for="HasAgeRestriction" class="form-control form-check-input p-3" type="checkbox" value="false" onchange="this.value = this.checked" />
                            <span asp-validation-for="HasAgeRestriction" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="Genre" class="control-label"></label>
                            <select asp-for="Genre" class="form-control form-select" asp-items="Html.GetEnumSelectList<BoardGameGenre>()"></select>
                            <span asp-validation-for="Genre" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="Type" class="control-label"></label>
                            <select asp-for="Type" class="form-control form-select" asp-items="Html.GetEnumSelectList<BoardGameType>()"></select>
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group pt-2">
                        <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

BordSpellen/Views/BoardGame/Index.cshtml
@using Core.Domain.Security.Roles
@using BordSpellen.Util
@model IEnumerable<Core.Domain.Data.Entities.BoardGame>

@{
    ViewData["Title"] = "Boardgames";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
            <tr class="text-center">
                <th>@Html.DisplayNameFor(model => model.Image)</th>
                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.Description)</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.ImageStringFromByteArray()" alt="@item.Name" style="max-width: 150px"/>
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole(UserRoles.Organiser))
                    {
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details</a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>
                        </td>
                    }
                </tr>  
            }
            </tbody>
        </table>
    </div>
</div>

@await Html.PartialAsync("_CreateItem", "BoardGame")